import 'package:fear_of_god/models/ShopItemType.model.dart';

import './ShopItem.model.dart';

final all_items = <ShopItem>[
  ShopItem(
    id: "1",
    name: "PANELLED LEATHER JACKET",
    price: 3583.00,
    description:
        "EXCLUSIVE TO OUR WEB STORE; THE PANELLED LEATHER JACKET IS ONE OF THE SIXTH COLLECTION TRUE STATEMENT PIECES. CONSTRUCTED FROM SOFT CALF LEATHER AND CUT SLIGHTLY HIGHER AT THE BACK FOR A FRESH NEW SILHOUETTE. CONTRAST MARBLE CALF LEATHER AND NUBUCK CALF LEATHER LEATHER BELT",
    imagePath: "assets/images/1.jpg",
    type: ShopItemType.OUTERWEAR,
  ),
  ShopItem(
    id: "2",
    name: "DENIM TRACK JACKET",
    price: 994.00,
    description:
        "CONSTRUCTED FROM JAPANESE SELVEDGE DENIM WITH A SCOOPED NECKLINE, ROUNDED COLLAR AND SHIRRED WAISTBAND WITH A COORDINATED BELT, THIS UNLINED JACKET IS A VERSATILE SPRING PIECE.",
    imagePath: "assets/images/2.jpg",
    type: ShopItemType.OUTERWEAR,
  ),
  ShopItem(
    id: "3",
    name: "ULTRASUEDE SHIRT JACKET",
    price: 1356.00,
    description:
        "THE SIGNATURE SHIRT JACKET IS ONE OF THE HERO PIECES OF THE SIXTH COLLECTION. THIS ITERATION, CONSTRUCTED FROM A SOFT YET STRUCTURED ULTRASUEDE WITH A ROUGH FINISH, IS UNLINED WITH OVERSIZED FLAP POCKETS AND CUFFS WITH HIDDEN VELCRO CLOSURES AND A STORM FLAP AT THE BACK.",
    imagePath: "assets/images/3.jpg",
    type: ShopItemType.OUTERWEAR,
  ),
  ShopItem(
    id: "4",
    name: "NYLON FIELD JACKET",
    price: 1175.00,
    description:
        "COMPOSED OF HEAVYWEIGHT JAPANESE NYLON, THE FIELD JACKET FEATURES A DIAMOND QUILTED IRIDESCENT INTERIOR NYLON LINING WITH PRIMALOFT FILL AND VELCRO SLEEVE CUFFS. THE OVERSIZED FIT ALLOWS THE PIECE TO BE LAYERED OVER A HOODIE, WHILE THE FOUR FRONT POCKETS PROVIDE ACCESS TO ESSENTIALS.",
    imagePath: "assets/images/4.jpg",
    type: ShopItemType.OUTERWEAR,
  ),
  ShopItem(
    id: "5",
    name: "SIXTH COLLECTION BOMBER JACKET",
    price: 1266.00,
    description:
        "THE SIXTH COLLECTION BOMBER IS CONSTRUCTED FROM A SOFT CORDUROY CANVAS AND FEATURES A CONTRASTING INSET CANVAS PANEL WITH A SILICON APPLIQUE ITERATION OF THE NEW FEAR OF GOD LOGO, AND A LUXURIOUS YET LOW KEY QUILTED IRIDESCENT NYLON LINING.",
    imagePath: "assets/images/5.jpg",
    type: ShopItemType.OUTERWEAR,
  ),
  ShopItem(
    id: "6",
    name: "SLIM JEAN",
    price: 812.00,
    description:
        "WITH A STREAMLINED CUT, CONSTRUCTED FROM A SOFT CORDUROY CANVAS AND A PERFECTLY POSITIONED BELT, THIS IS AN ELEVATED TAKE ON OUR NEW GO-TO EVERYDAY JEAN.",
    imagePath: "assets/images/6.jpg",
    type: ShopItemType.DENIM,
  ),
  ShopItem(
    id: "7",
    name: "SLIM DENIM JEAN",
    price: 631.00,
    description:
        "THE SLIM JEAN WITH A STREAMLINED CUT IN JAPANESE SELVEDGE DENIM WITH A SLASHED KNEE, DISTRESSED DETAILS AND PERFECTLY POSITIONED BELT IS OUR NEW GO-TO EVERYDAY JEAN.",
    imagePath: "assets/images/7.jpg",
    type: ShopItemType.DENIM,
  ),
  ShopItem(
    id: "8",
    name: "RELAXED DENIM JEAN",
    price: 631.00,
    description:
        "THE SLIM JEAN WITH A STREAMLINED CUT IN JAPANESE SELVEDGE DENIM WITH A SLASHED KNEE, DISTRESSED DETAILS AND PERFECTLY POSITIONED BELT IS OUR NEW GO-TO EVERYDAY JEAN.",
    imagePath: "assets/images/8.jpg",
    type: ShopItemType.DENIM,
  ),
  ShopItem(
    id: "9",
    name: "SLIM JEAN",
    price: 812.00,
    description:
        "WITH A STREAMLINED CUT, CONSTRUCTED FROM A SOFT CORDUROY CANVAS AND A PERFECTLY POSITIONED BELT, THIS IS AN ELEVATED TAKE ON OUR NEW GO-TO EVERYDAY JEAN.",
    imagePath: "assets/images/9.jpg",
    type: ShopItemType.DENIM,
  ),
  ShopItem(
    id: "10",
    name: "MOCK NECK 'FG' PULLOVER",
    price: 721.00,
    description:
        "PART OF OUR CORE COLLECTION, THIS MOCK NECK PULLOVER WITH A BOLD CHENILLE APPLIQUÉD LOGO IS AN ELEVATED TAKE ON THE EVERYDAY SWEATSHIRT. THE SIGNATURE OVERSIZED SILHOUETTE IS GIVEN STRUCTURE THANKS TO A HEAVY FRENCH TERRY CONSTRUCTION WITH TONAL RIB KNIT TRIM. ",
    imagePath: "assets/images/10.jpg",
    type: ShopItemType.TOP,
  ),
  ShopItem(
    id: "11",
    name: "EVERYDAY FULL ZIP HOODIE",
    price: 631.00,
    description:
        "AT THE HEART OF OUR CORE COLLECTION SITS THIS REASSURINGLY WEIGHTY FRENCH TERRY HOODIE WITH DROP SHOULDERS, A SPLIT KANGAROO POCKET AND SILICONE ZIPPER PULLS FOR EFFORTLESS EASE.",
    imagePath: "assets/images/11.jpg",
    type: ShopItemType.TOP,
  ),
  ShopItem(
    id: "12",
    name: "PLAID PULLOVER HENLEY",
    price: 540.00,
    description:
        "A LONG SLEEVED ITERATION OF THIS SEASON'S DEFINITIVE SHIRT WITH A MANDARIN COLLAR AND HENLEY NECKLINE. THE OVERSIZED FRONT FLAP POCKETS, EXTENDED EXAGGERATED CUFF AND BOX PLEAT AT THE BACK IMPART A TAILORED FEEL TO AN OTHERWISE RELAXED SILHOUETTE.",
    imagePath: "assets/images/12.jpg",
    type: ShopItemType.TOP,
  ),
  ShopItem(
    id: "13",
    name: "LONG SLEEVE HENLEY VINTAGE BLACK",
    price: 386.00,
    description:
        "PART OF OUR CORE COLLECTION, THIS LONG SLEEVE HENLEY IS CRAFTED OUT OF A LIGHTWEIGHT FRENCH TERRY WITH A BOLD COLORBLOCK DESIGN THAT EFFORTLESSLY ELEVATES THIS ESSENTIAL PIECE FROM OUT OF THE ORDINARY.",
    imagePath: "assets/images/13.jpg",
    type: ShopItemType.TOP,
  ),
  ShopItem(
    id: "14",
    name: "SHORT SLEEVE HALF ZIP TEE",
    price: 359.00,
    description:
        "THE SHORT SLEEVE HENLEY IS A FEAR OF GOD SIGNATURE STAPLE. CUT IN OUR SIGNATURE OVERSIZED SILHOUETTE AND CONSTRUCTED IN A LIGHT FRENCH TERRY FOR EVERYDAY WEAR, OR IT CAN BE LAYERED OVER A LONG SLEEVE TEE.",
    imagePath: "assets/images/14.jpg",
    type: ShopItemType.TOP,
  ),
  ShopItem(
    id: "15",
    name: "NYLON CARGO SNAP PANT",
    price: 903.00,
    description:
        "CONSTRUCTED FROM JAPANESE NYLON THIS PANT IS LIGHT ENOUGH TO WEAR IN ANY WEATHER, BUT HEAVY ENOUGH TO CONVEY QUALITY.",
    imagePath: "assets/images/15.jpg",
    type: ShopItemType.BOTTOM,
  ),
  ShopItem(
    id: "16",
    name: "NYLON SNAP CARGO PANT",
    price: 994.00,
    description:
        "THE NYLON CARGO PANT IS ONE OF THE HERO PIECES OF THE 6TH COLLECTION. CONSTRUCTED FROM JAPANESE NYLON, THIS PANT IS LIGHT ENOUGH TO WEAR IN ANY WEATHER, BUT HEAVY ENOUGH TO CONVEY QUALITY. DISTINCTIVE DETAILS INCLUDE METAL LOGO SNAPS RUNNING DOWN EACH LEG AND ULTRASUEDE LINED POCKETS FOR A FEELING OF LOW KEY LUXURY.",
    imagePath: "assets/images/16.jpg",
    type: ShopItemType.BOTTOM,
  ),
  ShopItem(
    id: "17",
    name: "NYLON CANVAS DOUBLE FRONT WORK PANT",
    price: 812.00,
    description:
        "INSPIRED BY UTILITARIAN WORKWEAR, THE NYLON CANVAS DOUBLE FRONT WORK PANT IS A STUDY IN CRAFTSMANSHIP. CONSTRUCTED FROM HEAVY JAPANESE CANVAS WITH NYLON PANELS, THIS HYPER STYLIZED WORK-MEETS-WADING PANT IS THE ULTIMATE EXPRESSION OF THE SIXTH COLLECTION. DISTINCTIVE DETAILS INCLUDE OUR NEW SILICONE LOGO TAG AT THE FRONT AND NYLON BELT STRAPS FOR FLAIR.",
    imagePath: "assets/images/17.jpg",
    type: ShopItemType.BOTTOM,
  ),
  ShopItem(
    id: "18",
    name: "JIUJITSU PANT",
    price: 812.00,
    description:
        "INSPIRED BY TRADITIONAL MARTIAL ARTS TROUSERS, OUR JIUJITSU PANT IS CONSTRUCTED OUT OF JAPANESE SELVEDGE CHINO AND STONEWASHED FOR A VINTAGE LOOK AND FEEL.",
    imagePath: "assets/images/18.jpg",
    type: ShopItemType.BOTTOM,
  ),
  ShopItem(
    id: "19",
    name: "RELAXED SWEATPANT",
    price: 721.00,
    description:
        "OUR RELAXED FIT SWEATPANT IS CONSTRUCTED OUT OF HEAVY FRENCH TERRY WITH A LOOSER CUT AND SLIGHT DROP CROTCH. A TONAL NYLON BELT AND INSET PANELS LEND AN ELEVATED EDGE.",
    imagePath: "assets/images/19.jpg",
    type: ShopItemType.BOTTOM,
  ),
  ShopItem(
    id: "20",
    name: "NYLON QUILTED PANT",
    price: 903.00,
    description:
        "CONSTRUCTED FROM JAPANESE NYLON THESE UNFILLED, QUILTED GRID PANTS ARE LINED IN A LIGHT COTTON JERSEY. SLIGHTLY TAPERED THEY FEATURE RIBBED COTTON ANKLE CUFFS, A SILICON LOGO TAG AT FRONT AND A NYLON BELT.",
    imagePath: "assets/images/20.jpg",
    type: ShopItemType.BOTTOM,
  ),
  ShopItem(
    id: "21",
    name: "CHELSEA SANTA FE BOOT",
    price: 721.00,
    description: "HANDCRAFTED IN ITALY, GOD GREY ITALIAN SUEDE.",
    imagePath: "assets/images/21.jpg",
    type: ShopItemType.FOOTWEAR,
  ),
  ShopItem(
    id: "22",
    name: "TEAR-AWAY MOC SNEAKER",
    price: 540.00,
    description: "HANDCRAFTED IN ITALY",
    imagePath: "assets/images/22.jpg",
    type: ShopItemType.FOOTWEAR,
  ),
];
