/// Flutter icons FogIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FogIcons
///      fonts:
///       - asset: fonts/FogIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class FogIcons {
  FogIcons._();

  static const _kFontFam = 'FogIcons';

  static const IconData user_fill = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart_fill = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xf290, fontFamily: _kFontFam);
}
